`cli` formatting of prompt to install missing package
tidymodels/recipes pull request #1061
Opened 2022-11-11 16:52 UTC by hfrick

closes #1060

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
data(ames, package = "modeldata")

ames_rec <-
  recipe(Sale_Price ~ ., data = ames) %>%
  step_spline_natural(Longitude, deg_free = 2) %>%
  step_spline_natural(Latitude, deg_free = 2)
#> 1 package (splines2) is needed for this step but is not installed.
#> Start a clean R session then run: install.packages("splines2")
#> 1 package (splines2) is needed for this step but is not installed.
#> Start a clean R session then run: install.packages("splines2")
```

<sup>Created on 2022-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2022-11-11 20:53 UTC, EmilHvitfeldt requested changes
I love it! great to see the the move to {cli}. Would you consider using `{.run }` to make the `install.packages(c("missing_pkg_1", "missing_pkg_2"))` clickable? I think that would be neat

https://cli.r-lib.org/reference/links.html?q=.run#click-to-run-code

2022-11-11 21:00 UTC, EmilHvitfeldt commented on R/pkg_check.R
> +      "{n_install_pkgs} package{?s} ({.pkg {install_pkg}}) {?is/are} needed for this step but {?is/are} not installed."
```suggestion
      "{n_install_pkgs} package{?s} ({.pkg {install_pkg}}) {?is/are} needed ",
      "for this step but {?is/are} not installed."
```

we can split up this string to keep it inside 80 chars

2022-11-14 13:21 UTC, hfrick commented
Oh yes, that is neat! We recommend starting a clean R session though so that conflicts a little with "just click here". Is the new session necessary? If not, I'd drop that and say "To install, run `install.packages("missing_pkg")`".

```
recipes_pkg_check(pkg = "missing_pkg", dependencies = NA)
1 package (missing_pkg) is needed for this step but is not installed.
Start a clean R session then run: install.packages("missing_pkg", dependencies = NA)
```

2022-11-14 21:29 UTC, hfrick commented
I assume we don't need a new session for the install (maybe after) so I've updated to a simple `To install run: `

2022-11-15 06:28 UTC, EmilHvitfeldt approved these changes
Love it!

2022-12-07 21:52 UTC, merged