Remove usage of `@keywords` and `@concept`, except for internal
tidymodels/recipes pull request #773
Opened 2021-08-18 19:28 UTC by juliasilge

Goodbye, somewhat random and uneven use of `@keywords` and `@concept`! :sassy_woman: We will still, of course, continue to use `@keywords internal` but we will now use `@family` instead of these other methods of organizing/linking documentation.

Related to #763 as a followup and continuation of that work.

I believe closes #709 but I would appreciate someone else confirming this.

2021-08-18 19:29 UTC, juliasilge commented
@hfrick I added you as reviewer but of course no rush

2021-08-18 19:47 UTC, EmilHvitfeldt commented
I believe that this PR (along with previous PRs) would close #709

2021-08-23 14:32 UTC, hfrick requested changes
Happy journey `@concept` and keywords! :wave:  I think one keyword internal got cleaned out which we still want, other than that: awesome, many thanks!

Yes, I think this closes #709

2021-08-23 14:42 UTC, juliasilge commented on R/kpca.R
> -#' @keywords datagen internal
Ah, thanks for catching that 🙌

2021-08-23 14:42 UTC, hfrick approved these changes

2021-08-23 15:18 UTC, merged